### PR TITLE
finish task_11

### PR DESCRIPTION
**Pull request by alenakuznetsova**

### CODE REVIEW

**Comment by AMashoshyna** [comment]
@alenakuznetsova add link to demo, please!

**Comment by AMashoshyna** [comment]
@alenakuznetsova html validator shows some errors in markup, which need to be fixed. let me know, if you need help deciphering the comments
here is the link: https://validator.w3.org/
you can paste code directly or insert link to demo

**Comment by alenakuznetsova** [comment]
@AMashoshyna I added demo link in readme file, fixed some mistakes, but I didn't understand why I have a problem with class "select-wrapper", could you please help me?

**Comment by lempiy** [comment]
@alenakuznetsova Element div not allowed as child of element label in this context. - You can not use div inside label tag.
should use span or similar inline element.

**Comment by alenakuznetsova** [comment]
@lempiy thank you, I fixed all mistakes. Thanks, guys.
 [Demo](https://alenakuznetsova.github.io/html5-form/)

**Pull request merged**
